### ISSUE TITLE
Suggestion: Use RelativePath parameter in web.contents call

### ISSUE THREAD

**Issue by hanksteen** [ITLec/PowerQueryBuilder#26]
First of all: Thanks for the great work!

Today the call to web.contents gets generated something like this.
Web.Contents(ServiceRootURL & "/incidentresolutions", [Headers=[Prefer="odata.include-annotations=*"],Query=[fetchXml="

My suggestion would be to change this to
Web.Contents(ServiceRootURL, [RelativePath="/incidentresolutions",Headers=[Prefer="odata.include-annotations=*"],Query=[fetchXml="

For me this changes is relevant when publishing to the Power BI service where I with the current solution will have to add web credentials to all urls. Using RelativePath I only need to add web credentials once.

**Comment by ITLec** [comment]
Thanks a lot hanksteen. We already implement your suggestion. We also include a big thanks for you in the latest release note.
